name: Update Prompt Daily

on:
  schedule:
    - cron: "0 4 * * *"   # Ogni giorno alle 04:00 UTC
  workflow_dispatch:       # Permette di avviarlo anche manualmente da GitHub

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater
        run: python update_prompt_full_calendar.py

      - name: Commit & Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add prompt.json
          git commit -m "Update prompt.json with latest site & courses" || echo "No changes to commit"
          git push
