name: Aggiorna prompt con calendario

on:
  schedule:
    - cron: "0 4 * * *" # ogni giorno alle 4:00 UTC
  workflow_dispatch: # permette di lanciarlo a mano

jobs:
  update-prompt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests beautifulsoup4

      - name: Aggiorna prompt
        run: python ./update_prompt_full_calendar.py

      - name: Commit & Push aggiornamenti
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add prompt.json
          git commit -m "🤖 Aggiornato prompt.json con calendario corsi" || echo "Nessuna modifica da committare"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
