name: Update prompt.json with courses

on:
  schedule:
    - cron: "0 2 * * *"   # ogni giorno alle 02:00 UTC
  workflow_dispatch:       # per avviarlo manualmente

jobs:
  update-prompt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update script
        run: |
          python update_prompt_full_calendar.py

      - name: Commit and push updated prompt.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add prompt.json
          git commit -m "Aggiornamento automatico prompt.json con calendario corsi"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
